### ISSUE TITLE
Any Q/A

### ISSUE THREAD

**Issue by lopestom** [DeadPo01/android_device_cubot_X70#1]
Here you can write any doubt if you have.
@DeadPo01

**Comment by DeadPo01** [comment]
![image](https://github.com/DeadPo01/android_device_cubot_X70/assets/70272456/7e0cbe90-2ae5-4254-9e44-d29368a51dc8)

what is this error means?

`build/make/core/Makefile:2236: error: real file "out/target/product/X70/obj/PACKAGING/recovery_intermediates/ramdisk_files-timestamp" depends on PHONY target "ALL"`

And what to try to do to solve it?

**Comment by lopestom** [comment]
> ![image](https://user-images.githubusercontent.com/70272456/270008235-7e0cbe90-2ae5-4254-9e44-d29368a51dc8.png)
> 
> what is this error means?
> 
> `build/make/core/Makefile:2236: error: real file "out/target/product/X70/obj/PACKAGING/recovery_intermediates/ramdisk_files-timestamp" depends on PHONY target "ALL"`
> 
> And what to try to do to solve it?

You not copied stock files to DT?!
https://github.com/DeadPo01/android_device_cubot_X70/tree/twrp-12.1/recovery/root/vendor/bin

About error: You need change DT - Settings - Visibility to `public`.
After that you can use Action-TWRP-Builder.

Only with personal Action you can compile Device Trees with private.

**Comment by lopestom** [comment]
Copied the twrp.dependencies to not show this error: https://github.com/DeadPo01/Action-TWRP-Builder/actions/runs/6276679807/job/17046892181#step:14:1

**Comment by lopestom** [comment]
Made some changes to check if there are still errors:
`Added choices that were empty.`
https://github.com/DeadPo01/Action-TWRP-Builder/actions/runs/6276679807/job/17046892181#step:16:389

But remember to put the firmware files in the files I left as an example copy_

**Comment by lopestom** [comment]
> ![image](https://user-images.githubusercontent.com/70272456/270008235-7e0cbe90-2ae5-4254-9e44-d29368a51dc8.png)
> 
> what is this error means?
> 
> `build/make/core/Makefile:2236: error: real file "out/target/product/X70/obj/PACKAGING/recovery_intermediates/ramdisk_files-timestamp" depends on PHONY target "ALL"`
> 
> And what to try to do to solve it?

Without you having yet placed the missing original firmware files in the device tree - copy_; I decided to do compilation tests to see if an img file will be created.
Still patching DT based on TWRP Device Tree for Dimensity, still making it happen to make it good for you.

I have a DT that I made a long time ago. But I'm not going to share it yet. Many users are imitators and do not give due credit. This DT is really the study of time and dedication. Some parts and information were shared on the 4pda forum and I know some users copied it - that's ok, I did it on purpose.

When I have the img ready I will let you know so you can test it. But again I warn you about putting the original firmware files on the DT.

**Comment by DeadPo01** [comment]
Ok, i understand. Will add files.

**Comment by DeadPo01** [comment]
Added files, same error =( 
![image](https://github.com/DeadPo01/android_device_cubot_X70/assets/70272456/9a2f7ede-afb8-4d8b-8f38-09fe6dc9ba29)

**Comment by lopestom** [comment]
> Added files, same error [image]


I made a few attempts with this DT and became suspicious of something. So I decided to make some attempts with another DT that has already compiled the img file more than 10 times/files.
Unfortunately, all attempts had errors and even different errors.
```
build/make/core/board_config.mk:902: error: Should not set BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT if not building vendor_boot image.
02:08:16 dumpvars failed with: exit status 1
In file included from build/make/core/config.mk:313:
In file included from build/make/core/envsetup.mk:323:
build/make/core/board_config.mk:902: error: Should not set BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT if not building vendor_boot image.
02:08:16 dumpvars failed with: exit status 1
```

I think people were tinkering with something in the TWRP source code or there is something new. As I made the attempts 8 hours ago, I will make more attempts soon.

**Comment by lopestom** [comment]
> Added files, same error =( 

Look your private message in 4pda.
